// Generated by CIRCT firtool-1.62.1
module RegModule(
  input        clock,
               reset,
               io_sel,
  output [7:0] io_out,
  output       _cond_pred_RegModule__I__local__I___T,
  output [7:0] _reg_signals_RegModule__I__local__I__regA,
               _reg_signals_RegModule__I__local__I__regB
);

  reg [7:0] regA;
  reg [7:0] regB;
  always @(posedge clock) begin
    if (reset) begin
      regA <= 8'h0;
      regB <= 8'h64;
    end
    else begin
      regA <= regA + 8'h1;
      regB <= regB - 8'h1;
    end
  end // always @(posedge)
  assign io_out = io_sel ? regB : regA;
  assign _cond_pred_RegModule__I__local__I___T = ~io_sel;
  assign _reg_signals_RegModule__I__local__I__regA = regA;
  assign _reg_signals_RegModule__I__local__I__regB = regB;
endmodule

