// Generated by CIRCT firtool-1.43.0
module RegModule(
  input        clock,
               reset,
               io_sel,
  output [7:0] io_out_0_0,
               io_out_0_1,
               io_out_0_2,
               io_out_1_0,
               io_out_1_1,
               io_out_1_2,
  output       _cp__s0,
  output [7:0] _rs__s0,
               _rs__s1,
               _rs__s10,
               _rs__s11,
               _rs__s2,
               _rs__s3,
               _rs__s4,
               _rs__s5,
               _rs__s6,
               _rs__s7,
               _rs__s8,
               _rs__s9
);

  reg [7:0] regA_0_0;
  reg [7:0] regB_1_2;
  always @(posedge clock) begin
    if (reset) begin
      regA_0_0 <= 8'h0;
      regB_1_2 <= 8'h70;
    end
    else begin
      regA_0_0 <= regA_0_0 + 8'h1;
      regB_1_2 <= regB_1_2 - 8'h1;
    end
  end // always @(posedge)
  assign io_out_0_0 = io_sel ? 8'h64 : regA_0_0;
  assign io_out_0_1 = io_sel ? 8'h65 : 8'h0;
  assign io_out_0_2 = io_sel ? 8'h66 : 8'h0;
  assign io_out_1_0 = io_sel ? 8'h6E : 8'h0;
  assign io_out_1_1 = io_sel ? 8'h6F : 8'h0;
  assign io_out_1_2 = io_sel ? regB_1_2 : 8'h0;
  assign _cp__s0 = ~io_sel;
  assign _rs__s0 = regA_0_0;
  assign _rs__s1 = 8'h0;
  assign _rs__s10 = 8'h6F;
  assign _rs__s11 = regB_1_2;
  assign _rs__s2 = 8'h0;
  assign _rs__s3 = 8'h0;
  assign _rs__s4 = 8'h0;
  assign _rs__s5 = 8'h0;
  assign _rs__s6 = 8'h64;
  assign _rs__s7 = 8'h65;
  assign _rs__s8 = 8'h66;
  assign _rs__s9 = 8'h6E;
endmodule

