// Generated by CIRCT firtool-1.62.1
module InnerModule(
  input        io_sel,
  input  [7:0] io_inputA,
               io_inputB,
  output [7:0] io_innerOut,
  output       _mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel
);

  assign io_innerOut = io_sel ? io_inputB : io_inputA;
  assign _mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel = io_sel;
endmodule

module MidLevelModule(
  input        io_midSel1,
               io_midSel2,
  input  [7:0] io_midInA,
               io_midInB,
               io_midInC,
               io_midInD,
  output [7:0] io_midOut,
  output       _mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel,
               _mux_cond_topInst__I__mid__I__local__I__io__S__midSel1,
               _mux_cond_topInst__I__mid__I__local__I__io__S__midSel2
);

  wire [7:0] _inner_io_innerOut;
  InnerModule inner (
    .io_sel                                                       (io_midSel2),
    .io_inputA                                                    (io_midInC),
    .io_inputB                                                    (io_midInD),
    .io_innerOut                                                  (_inner_io_innerOut),
    ._mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel
      (_mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel)
  );
  assign io_midOut = io_midSel1 ? _inner_io_innerOut : io_midSel2 ? io_midInB : io_midInA;
  assign _mux_cond_topInst__I__mid__I__local__I__io__S__midSel1 = io_midSel1;
  assign _mux_cond_topInst__I__mid__I__local__I__io__S__midSel2 = io_midSel2;
endmodule

module TopModule(
  input        clock,
               reset,
  input  [1:0] io_topSel1,
               io_topSel2,
  input        io_topSel3,
  input  [7:0] io_dataIn1,
               io_dataIn2,
               io_dataIn3,
               io_dataIn4,
               io_dataIn5,
               io_dataIn6,
  output [7:0] io_finalOut,
  output       _mux_cond_topInst__I__local__I___io_finalOut_T,
               _mux_cond_topInst__I__local__I___io_finalOut_switchResult_T,
               _mux_cond_topInst__I__local__I___io_finalOut_switchResult_T_2,
               _mux_cond_topInst__I__local__I__io__S__topSel3,
               _mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel,
               _mux_cond_topInst__I__mid__I__local__I__io__S__midSel1,
               _mux_cond_topInst__I__mid__I__local__I__io__S__midSel2
);

  wire [7:0]      _mid_io_midOut;
  wire            _io_finalOut_T_1 = io_topSel2 == 2'h0;
  wire            _io_finalOut_T_4 = io_topSel2 == 2'h1;
  wire [3:0][7:0] _GEN =
    {{8'h0},
     {io_topSel3 ? (io_topSel1[0] ? io_dataIn6 : io_dataIn5) : io_dataIn1},
     {io_topSel3 ? io_dataIn3 : io_dataIn4},
     {io_topSel3 ? io_dataIn2 : io_dataIn1}};
  MidLevelModule mid (
    .io_midSel1                                                   (io_topSel1[0]),
    .io_midSel2                                                   (io_topSel3),
    .io_midInA                                                    (io_dataIn1),
    .io_midInB                                                    (io_dataIn2),
    .io_midInC                                                    (io_dataIn3),
    .io_midInD                                                    (io_dataIn4),
    .io_midOut                                                    (_mid_io_midOut),
    ._mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel
      (_mux_cond_topInst__I__mid__I__inner__I__local__I__io__S__sel),
    ._mux_cond_topInst__I__mid__I__local__I__io__S__midSel1
      (_mux_cond_topInst__I__mid__I__local__I__io__S__midSel1),
    ._mux_cond_topInst__I__mid__I__local__I__io__S__midSel2
      (_mux_cond_topInst__I__mid__I__local__I__io__S__midSel2)
  );
  assign io_finalOut = io_topSel1[1] ? _mid_io_midOut : _GEN[io_topSel2];
  assign _mux_cond_topInst__I__local__I___io_finalOut_T = io_topSel1[1];
  assign _mux_cond_topInst__I__local__I___io_finalOut_switchResult_T =
    ~_io_finalOut_T_1 & _io_finalOut_T_4 & ~io_topSel3;
  assign _mux_cond_topInst__I__local__I___io_finalOut_switchResult_T_2 =
    ~(_io_finalOut_T_1 | _io_finalOut_T_4) & io_topSel2 == 2'h2 & io_topSel1[0];
  assign _mux_cond_topInst__I__local__I__io__S__topSel3 = io_topSel3;
endmodule

