// Generated by CIRCT firtool-1.62.1
module InnerModule (
    input        io_sel,
    input  [7:0] io_inputA,
    io_inputB,
    output [7:0] io_innerOut
);

  assign io_innerOut = io_sel ? io_inputB : io_inputA;
endmodule

module MidLevelModule (
    input        io_midSel1,
    io_midSel2,
    input  [7:0] io_midInA,
    io_midInB,
    io_midInC,
    io_midInD,
    output [7:0] io_midOut
);

  wire [7:0] _inner_io_innerOut;
  InnerModule inner (
      .io_sel     (io_midSel2),
      .io_inputA  (io_midInC),
      .io_inputB  (io_midInD),
      .io_innerOut(_inner_io_innerOut)
  );
  assign io_midOut = io_midSel1 ? _inner_io_innerOut : io_midSel2 ? io_midInB : io_midInA;
endmodule

module TopModule (
    input        clock,
    reset,
    input  [1:0] io_topSel1,
    io_topSel2,
    input        io_topSel3,
    input  [7:0] io_dataIn1,
    io_dataIn2,
    io_dataIn3,
    io_dataIn4,
    io_dataIn5,
    io_dataIn6,
    output [7:0] io_finalOut
);

  wire [7:0] _mid_io_midOut;
  wire [3:0][7:0] _GEN = {
    {8'h0},
    {io_topSel3 ? (io_topSel1[0] ? io_dataIn6 : io_dataIn5) : io_dataIn1},
    {io_topSel3 ? io_dataIn3 : io_dataIn4},
    {io_topSel3 ? io_dataIn2 : io_dataIn1}
  };
  MidLevelModule mid (
      .io_midSel1(io_topSel1[0]),
      .io_midSel2(io_topSel3),
      .io_midInA (io_dataIn1),
      .io_midInB (io_dataIn2),
      .io_midInC (io_dataIn3),
      .io_midInD (io_dataIn4),
      .io_midOut (_mid_io_midOut)
  );
  assign io_finalOut = io_topSel1[1] ? _mid_io_midOut : _GEN[io_topSel2];
endmodule

