// Generated by CIRCT firtool-1.43.0
module UART_tx(
  input        clock,
               reset,
               io_i_tx_trig,
  input  [7:0] io_i_data,
  output       io_o_tx_busy,
               io_o_tx_done,
               io_o_serial_data
);

  reg [7:0] clkCnterReg;
  reg [3:0] bitCnterReg;
  reg [7:0] inDataReg;
  reg       outDataReg;
  reg       outTxBusyReg;
  reg       outTxDoneReg;
  reg [1:0] stateReg;
  always @(posedge clock) begin
    if (reset) begin
      clkCnterReg <= 8'h0;
      bitCnterReg <= 4'h0;
      inDataReg <= 8'h0;
      outDataReg <= 1'h1;
      outTxBusyReg <= 1'h0;
      outTxDoneReg <= 1'h0;
      stateReg <= 2'h0;
    end
    else begin
      automatic logic _GEN;
      automatic logic _GEN_0;
      automatic logic _GEN_1;
      _GEN = stateReg == 2'h1;
      _GEN_0 = clkCnterReg < 8'h56;
      _GEN_1 = stateReg == 2'h2;
      if (|stateReg) begin
        automatic logic [7:0]      _GEN_2;
        automatic logic [3:0]      _GEN_3;
        automatic logic [7:0]      _GEN_4 = inDataReg >> bitCnterReg;
        automatic logic [3:0][7:0] _GEN_5;
        automatic logic [3:0][1:0] _GEN_6;
        _GEN_2 = _GEN_0 ? clkCnterReg + 8'h1 : 8'h0;
        _GEN_3 = bitCnterReg + 4'h1;
        _GEN_5 = {{_GEN_2}, {_GEN_2}, {_GEN_2}, {clkCnterReg}};
        clkCnterReg <= _GEN_5[stateReg];
        if (_GEN) begin
          if (~_GEN_0) begin
            bitCnterReg <= _GEN_3;
            outDataReg <= _GEN_4[0];
          end
        end
        else if (~_GEN_1 | _GEN_0) begin
        end
        else begin
          if (bitCnterReg[3])
            bitCnterReg <= 4'h0;
          else
            bitCnterReg <= _GEN_3;
          outDataReg <= bitCnterReg[3] | _GEN_4[0];
        end
        _GEN_6 =
          {{{2{_GEN_0}}},
           {{1'h1, ~(_GEN_0 | ~(bitCnterReg[3]))}},
           {_GEN_0 ? 2'h1 : 2'h2},
           {stateReg}};
        stateReg <= _GEN_6[stateReg];
      end
      else begin
        clkCnterReg <= 8'h0;
        bitCnterReg <= 4'h0;
        outDataReg <= ~io_i_tx_trig & outDataReg;
        stateReg <= {1'h0, io_i_tx_trig};
      end
      if (~(|stateReg) & io_i_tx_trig)
        inDataReg <= io_i_data;
      outTxBusyReg <= |stateReg;
      outTxDoneReg <=
        (|stateReg) & (~(_GEN | _GEN_1) & (&stateReg) & ~_GEN_0 | outTxDoneReg);
    end
  end // always @(posedge)
  assign io_o_tx_busy = outTxBusyReg;
  assign io_o_tx_done = outTxDoneReg;
  assign io_o_serial_data = outDataReg;
endmodule

