// Generated by CIRCT firtool-1.62.1
module RegModule(
  input        clock,
               reset,
               io_sel,
  output [7:0] io_out
);

  reg [7:0] regA;
  reg [7:0] regB;
  always @(posedge clock) begin
    if (reset) begin
      regA <= 8'h0;
      regB <= 8'h64;
    end
    else begin
      regA <= regA + 8'h1;
      regB <= regB - 8'h1;
    end
  end // always @(posedge)
  assign io_out = io_sel ? regB : regA;
endmodule

