// Generated by CIRCT firtool-1.43.0
module RocketALU(
  input         clock,
                reset,
                io_dw,
  input  [4:0]  io_fn,
  input  [63:0] io_in2,
                io_in1,
  output [63:0] io_out,
                io_adder_out,
  output        io_cmp_out
);

  wire [63:0] in2_inv = {64{io_fn[3]}} ^ io_in2;
  wire [63:0] in1_xor_in2 = io_in1 ^ in2_inv;
  wire [63:0] _io_adder_out_output = io_in1 + in2_inv + {63'h0, io_fn[3]};
  wire        slt =
    io_in1[63] == io_in2[63]
      ? _io_adder_out_output[63]
      : io_fn[1] ? io_in2[63] : io_in1[63];
  wire [31:0] shin_hi = io_dw ? io_in1[63:32] : {32{io_fn[3] & io_in1[31]}};
  wire        _GEN = io_fn == 5'h13;
  wire        _GEN_0 = io_fn == 5'h5 | io_fn == 5'hB;
  wire [31:0] _GEN_1 = {io_in1[31:16], 16'h0} | shin_hi & 32'hFFFF;
  wire [31:0] _GEN_2 =
    {{io_in1[15:0], _GEN_1[31:24]} & 24'hFF00FF, 8'h0} | _GEN_1 & 32'hFF00FF;
  wire [31:0] _GEN_3 =
    {{io_in1[7:0], _GEN_2[31:12]} & 28'hF0F0F0F, 4'h0} | _GEN_2 & 32'hF0F0F0F;
  wire [45:0] _GEN_4 =
    {io_in1[3:0], _GEN_3, _GEN_2[7:4], _GEN_1[11:8], _GEN_1[15:14]} & 46'h333333333333;
  wire [31:0] _GEN_5 = _GEN_4[45:14] | _GEN_3 & 32'h33333333;
  wire [1:0]  _GEN_6 = _GEN_4[11:10] | _GEN_2[5:4];
  wire [7:0]  _GEN_7 = {_GEN_4[5:0], 2'h0} | {_GEN_1[15:12], shin_hi[19:16]} & 8'h33;
  wire [54:0] _GEN_8 =
    {io_in1[1:0],
     _GEN_5,
     _GEN_3[3:2],
     _GEN_6,
     _GEN_2[7:6],
     _GEN_1[9:8],
     _GEN_7,
     shin_hi[19:18],
     shin_hi[21:20],
     shin_hi[23]} & 55'h55555555555555;
  wire [63:0] shin =
    _GEN_0 | io_fn == 5'h12 | _GEN
      ? {shin_hi, io_in1[31:0]}
      : {io_in1[0],
         _GEN_8[54:23] | _GEN_5 & 32'h55555555,
         _GEN_5[1],
         _GEN_8[21] | _GEN_3[2],
         {_GEN_3[3], 1'h0} | _GEN_6 & 2'h1,
         _GEN_8[18:15] | {_GEN_2[7:6], _GEN_1[9:8]} & 4'h5,
         _GEN_8[14:7] | _GEN_7 & 8'h55,
         _GEN_7[1],
         _GEN_8[5] | shin_hi[18],
         shin_hi[19],
         shin_hi[20],
         {_GEN_8[2:0], 1'h0} | {shin_hi[23:22], shin_hi[25:24]} & 4'h5,
         shin_hi[25],
         shin_hi[26],
         shin_hi[27],
         shin_hi[28],
         shin_hi[29],
         shin_hi[30],
         shin_hi[31]};
  wire [64:0] _GEN_9 =
    $signed($signed({io_fn[3] & shin[63], shin})
            >>> {59'h0, io_in2[5] & io_dw, io_in2[4:0]});
  wire [15:0] _GEN_10 =
    {{_GEN_9[23:16], _GEN_9[31:28]} & 12'hF0F, 4'h0} | {_GEN_9[31:24], _GEN_9[39:32]}
    & 16'hF0F;
  wire [37:0] _GEN_11 =
    {_GEN_9[11:8],
     _GEN_9[15:12],
     _GEN_9[19:16],
     _GEN_10,
     _GEN_9[39:36],
     _GEN_9[43:40],
     _GEN_9[47:46]} & 38'h3333333333;
  wire [7:0]  _GEN_12 = _GEN_11[37:30] | {_GEN_9[15:12], _GEN_9[19:16]} & 8'h33;
  wire [15:0] _GEN_13 = _GEN_11[29:14] | _GEN_10 & 16'h3333;
  wire [1:0]  _GEN_14 = _GEN_11[11:10] | _GEN_9[37:36];
  wire [7:0]  _GEN_15 = {_GEN_11[5:0], 2'h0} | {_GEN_9[47:44], _GEN_9[51:48]} & 8'h33;
  wire [50:0] _GEN_16 =
    {_GEN_9[5:4],
     _GEN_9[7:6],
     _GEN_9[9:8],
     _GEN_12,
     _GEN_13,
     _GEN_10[3:2],
     _GEN_14,
     _GEN_9[39:38],
     _GEN_9[41:40],
     _GEN_15,
     _GEN_9[51:50],
     _GEN_9[53:52],
     _GEN_9[55]} & 51'h5555555555555;
  wire        _GEN_17 = io_fn == 5'h6;
  wire        _GEN_18 = io_fn == 5'h19;
  wire [63:0] out =
    io_fn == 5'hA | io_fn == 5'h0
      ? _io_adder_out_output
      : {63'h0, io_fn > 5'hB & ~(io_fn[4]) & slt}
        | (io_fn == 5'h4 | _GEN_17 | _GEN_18 | io_fn == 5'h1A ? in1_xor_in2 : 64'h0)
        | (_GEN_17 | io_fn == 5'h7 | _GEN_18 | io_fn == 5'h18 ? io_in1 & in2_inv : 64'h0)
        | (_GEN_0 | _GEN ? _GEN_9[63:0] : 64'h0)
        | (io_fn == 5'h1
             ? {_GEN_9[0],
                _GEN_9[1],
                _GEN_9[2],
                _GEN_9[3],
                _GEN_9[4],
                _GEN_16[50:47] | {_GEN_9[7:6], _GEN_9[9:8]} & 4'h5,
                _GEN_16[46:39] | _GEN_12 & 8'h55,
                _GEN_16[38:23] | _GEN_13 & 16'h5555,
                _GEN_13[1],
                _GEN_16[21] | _GEN_10[2],
                {_GEN_10[3], 1'h0} | _GEN_14 & 2'h1,
                _GEN_16[18:15] | {_GEN_9[39:38], _GEN_9[41:40]} & 4'h5,
                _GEN_16[14:7] | _GEN_15 & 8'h55,
                _GEN_15[1],
                _GEN_16[5] | _GEN_9[50],
                _GEN_9[51],
                _GEN_9[52],
                {_GEN_16[2:0], 1'h0} | {_GEN_9[55:54], _GEN_9[57:56]} & 4'h5,
                _GEN_9[57],
                _GEN_9[58],
                _GEN_9[59],
                _GEN_9[60],
                _GEN_9[61],
                _GEN_9[62],
                _GEN_9[63]}
             : 64'h0);
  assign io_out = io_dw ? out : {{32{out[31]}}, out[31:0]};
  assign io_adder_out = _io_adder_out_output;
  assign io_cmp_out = io_fn[0] ^ (io_fn[3] ? slt : in1_xor_in2 == 64'h0);
endmodule

