// Generated by CIRCT firtool-1.51.0
module RocketALU(
  input         clock,
                reset,
                io_dw,
  input  [4:0]  io_fn,
  input  [63:0] io_in2,
                io_in1,
  output [63:0] io_out,
                io_adder_out,
  output        io_cmp_out,
                _mux_cond_RocketALU__M__RocketALU__S___bext_mask_T_1,
                _mux_cond_RocketALU__M__RocketALU__S___in2_inv_T,
                _mux_cond_RocketALU__M__RocketALU__S___io_cmp_out_T_2,
                _mux_cond_RocketALU__M__RocketALU__S___io_out_T_1,
                _mux_cond_RocketALU__M__RocketALU__S___logic_T_14,
                _mux_cond_RocketALU__M__RocketALU__S___logic_T_6,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_1,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_10,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_13,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_16,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_19,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_22,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_4,
                _mux_cond_RocketALU__M__RocketALU__S___orcb_T_7,
                _mux_cond_RocketALU__M__RocketALU__S___out_T,
                _mux_cond_RocketALU__M__RocketALU__S___out_T_2,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_1,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_10,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_11,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_12,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_13,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_14,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_15,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_16,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_17,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_18,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_19,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_20,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_21,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_22,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_23,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_24,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_25,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_26,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_27,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_28,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_29,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_30,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_31,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_32,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_33,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_34,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_35,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_36,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_37,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_38,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_39,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_40,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_41,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_42,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_43,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_44,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_45,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_46,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_47,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_48,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_49,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_5,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_50,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_51,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_52,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_53,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_54,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_55,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_56,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_57,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_58,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_59,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_6,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_60,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_61,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_62,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_63,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_64,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_65,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_66,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_67,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_68,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_69,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_7,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_8,
                _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_9,
                _mux_cond_RocketALU__M__RocketALU__S___rot_shamt_T,
                _mux_cond_RocketALU__M__RocketALU__S___rotin_T,
                _mux_cond_RocketALU__M__RocketALU__S___rotout_T,
                _mux_cond_RocketALU__M__RocketALU__S___rotout_T_2,
                _mux_cond_RocketALU__M__RocketALU__S___shin_T_7,
                _mux_cond_RocketALU__M__RocketALU__S___shin_hi_32_T_3,
                _mux_cond_RocketALU__M__RocketALU__S___shin_hi_T,
                _mux_cond_RocketALU__M__RocketALU__S___shout_T_4,
                _mux_cond_RocketALU__M__RocketALU__S___shout_T_6,
                _mux_cond_RocketALU__M__RocketALU__S___slt_T_2,
                _mux_cond_RocketALU__M__RocketALU__S___slt_T_4,
                _mux_cond_RocketALU__M__RocketALU__S___tz_in_T_116,
                _mux_cond_RocketALU__M__RocketALU__S___tz_in_T_118,
                _mux_cond_RocketALU__M__RocketALU__S___tz_in_T_120,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_12,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_14,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_16,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_18,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_20,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_3,
                _mux_cond_RocketALU__M__RocketALU__S___unary_T_8,
                _mux_cond_RocketALU__M__RocketALU__S__io__s__cmp_out,
                _cond_pred_RocketALU__M__RocketALU__S___T_1
);

  wire [63:0]      in2_inv = {64{io_fn[3]}} ^ io_in2;
  wire [63:0]      in1_xor_in2 = io_in1 ^ in2_inv;
  wire [63:0]      _io_adder_out_T_3 = io_in1 + in2_inv + {63'h0, io_fn[3]};
  wire             _slt_T_2 = io_in1[63] == io_in2[63];
  wire             slt =
    _slt_T_2 ? _io_adder_out_T_3[63] : io_fn[1] ? io_in2[63] : io_in1[63];
  wire             _io_cmp_out_output =
    io_fn[0] ^ (io_fn[3] ? slt : in1_xor_in2 == 64'h0);
  wire             _shin_hi_32_T_3 = io_fn[3] & io_in1[31];
  wire [31:0]      shin_hi = io_dw ? io_in1[63:32] : {32{_shin_hi_32_T_3}};
  wire             _shout_T = io_fn == 5'h5;
  wire             _shout_T_1 = io_fn == 5'hB;
  wire             _bext_mask_T = io_fn == 5'h13;
  wire             _shin_T_6 = _shout_T | _shout_T_1 | io_fn == 5'h12 | _bext_mask_T;
  wire [31:0]      _GEN = {io_in1[31:16], 16'h0} | shin_hi & 32'hFFFF;
  wire [31:0]      _GEN_0 =
    {{io_in1[15:0], _GEN[31:24]} & 24'hFF00FF, 8'h0} | _GEN & 32'hFF00FF;
  wire [31:0]      _GEN_1 =
    {{io_in1[7:0], _GEN_0[31:12]} & 28'hF0F0F0F, 4'h0} | _GEN_0 & 32'hF0F0F0F;
  wire [45:0]      _GEN_2 =
    {io_in1[3:0], _GEN_1, _GEN_0[7:4], _GEN[11:8], _GEN[15:14]} & 46'h333333333333;
  wire [31:0]      _GEN_3 = _GEN_2[45:14] | _GEN_1 & 32'h33333333;
  wire [1:0]       _GEN_4 = _GEN_2[11:10] | _GEN_0[5:4];
  wire [7:0]       _GEN_5 = {_GEN_2[5:0], 2'h0} | {_GEN[15:12], shin_hi[19:16]} & 8'h33;
  wire [54:0]      _GEN_6 =
    {io_in1[1:0],
     _GEN_3,
     _GEN_1[3:2],
     _GEN_4,
     _GEN_0[7:6],
     _GEN[9:8],
     _GEN_5,
     shin_hi[19:18],
     shin_hi[21:20],
     shin_hi[23]} & 55'h55555555555555;
  wire [63:0]      shin =
    _shin_T_6
      ? {shin_hi, io_in1[31:0]}
      : {io_in1[0],
         _GEN_6[54:23] | _GEN_3 & 32'h55555555,
         _GEN_3[1],
         _GEN_6[21] | _GEN_1[2],
         {_GEN_1[3], 1'h0} | _GEN_4 & 2'h1,
         _GEN_6[18:15] | {_GEN_0[7:6], _GEN[9:8]} & 4'h5,
         _GEN_6[14:7] | _GEN_5 & 8'h55,
         _GEN_5[1],
         _GEN_6[5] | shin_hi[18],
         shin_hi[19],
         shin_hi[20],
         {_GEN_6[2:0], 1'h0} | {shin_hi[23:22], shin_hi[25:24]} & 4'h5,
         shin_hi[25],
         shin_hi[26],
         shin_hi[27],
         shin_hi[28],
         shin_hi[29],
         shin_hi[30],
         shin_hi[31]};
  wire [64:0]      _shout_r_T_5 =
    $signed($signed({io_fn[3] & shin[63], shin})
            >>> {59'h0, io_in2[5] & io_dw, io_in2[4:0]});
  wire [15:0]      _GEN_7 =
    {{_shout_r_T_5[23:16], _shout_r_T_5[31:28]} & 12'hF0F, 4'h0}
    | {_shout_r_T_5[31:24], _shout_r_T_5[39:32]} & 16'hF0F;
  wire [37:0]      _GEN_8 =
    {_shout_r_T_5[11:8],
     _shout_r_T_5[15:12],
     _shout_r_T_5[19:16],
     _GEN_7,
     _shout_r_T_5[39:36],
     _shout_r_T_5[43:40],
     _shout_r_T_5[47:46]} & 38'h3333333333;
  wire [7:0]       _GEN_9 =
    _GEN_8[37:30] | {_shout_r_T_5[15:12], _shout_r_T_5[19:16]} & 8'h33;
  wire [15:0]      _GEN_10 = _GEN_8[29:14] | _GEN_7 & 16'h3333;
  wire [1:0]       _GEN_11 = _GEN_8[11:10] | _shout_r_T_5[37:36];
  wire [7:0]       _GEN_12 =
    {_GEN_8[5:0], 2'h0} | {_shout_r_T_5[47:44], _shout_r_T_5[51:48]} & 8'h33;
  wire [50:0]      _GEN_13 =
    {_shout_r_T_5[5:4],
     _shout_r_T_5[7:6],
     _shout_r_T_5[9:8],
     _GEN_9,
     _GEN_10,
     _GEN_7[3:2],
     _GEN_11,
     _shout_r_T_5[39:38],
     _shout_r_T_5[41:40],
     _GEN_12,
     _shout_r_T_5[51:50],
     _shout_r_T_5[53:52],
     _shout_r_T_5[55]} & 51'h5555555555555;
  wire             _shout_T_4 = _shout_T | _shout_T_1 | _bext_mask_T;
  wire             _shout_T_6 = io_fn == 5'h1;
  wire             _logic_T_8 = io_fn == 5'h6;
  wire             _logic_T_11 = io_fn == 5'h19;
  wire             _logic_T_6 = io_fn == 5'h4 | _logic_T_8 | _logic_T_11 | io_fn == 5'h1A;
  wire             _logic_T_14 =
    _logic_T_8 | io_fn == 5'h7 | _logic_T_11 | io_fn == 5'h18;
  wire [1:0]       _tz_in_T_3 = {~io_dw, ~(io_in2[0])};
  wire [15:0]      _GEN_14 =
    {{io_in1[23:16], io_in1[31:28]} & 12'hF0F, 4'h0} | {io_in1[31:24], io_in1[39:32]}
    & 16'hF0F;
  wire [37:0]      _GEN_15 =
    {io_in1[11:8],
     io_in1[15:12],
     io_in1[19:16],
     _GEN_14,
     io_in1[39:36],
     io_in1[43:40],
     io_in1[47:46]} & 38'h3333333333;
  wire [7:0]       _GEN_16 = {io_in1[15:12], io_in1[19:16]} & 8'h33;
  wire [7:0]       _GEN_17 = _GEN_15[37:30] | _GEN_16;
  wire [15:0]      _GEN_18 = _GEN_15[29:14] | _GEN_14 & 16'h3333;
  wire [1:0]       _GEN_19 = _GEN_15[11:10] | io_in1[37:36];
  wire [7:0]       _GEN_20 =
    {_GEN_15[5:0], 2'h0} | {io_in1[47:44], io_in1[51:48]} & 8'h33;
  wire [50:0]      _GEN_21 =
    {io_in1[5:4],
     io_in1[7:6],
     io_in1[9:8],
     _GEN_17,
     _GEN_18,
     _GEN_14[3:2],
     _GEN_19,
     io_in1[39:38],
     io_in1[41:40],
     _GEN_20,
     io_in1[51:50],
     io_in1[53:52],
     io_in1[55]} & 51'h5555555555555;
  wire [3:0]       _GEN_22 = {io_in1[7:6], io_in1[9:8]} & 4'h5;
  wire [7:0]       _GEN_23 = {{io_in1[11:8], io_in1[15:14]} & 6'h33, 2'h0} | _GEN_16;
  wire [18:0]      _GEN_24 =
    {io_in1[5:4],
     io_in1[7:6],
     io_in1[9:8],
     _GEN_23,
     io_in1[19:18],
     io_in1[21:20],
     io_in1[23]} & 19'h55555;
  wire [3:0][63:0] _GEN_25 =
    {{{32'h1,
       io_in1[0],
       io_in1[1],
       io_in1[2],
       io_in1[3],
       io_in1[4],
       _GEN_24[18:15] | _GEN_22,
       _GEN_24[14:7] | _GEN_23 & 8'h55,
       _GEN_23[1],
       _GEN_24[5] | io_in1[18],
       io_in1[19],
       io_in1[20],
       {_GEN_24[2:0], 1'h0} | {io_in1[23:22], io_in1[25:24]} & 4'h5,
       io_in1[25],
       io_in1[26],
       io_in1[27],
       io_in1[28],
       io_in1[29],
       io_in1[30],
       io_in1[31]}},
     {{32'h1, io_in1[31:0]}},
     {{io_in1[0],
       io_in1[1],
       io_in1[2],
       io_in1[3],
       io_in1[4],
       _GEN_21[50:47] | _GEN_22,
       _GEN_21[46:39] | _GEN_17 & 8'h55,
       _GEN_21[38:23] | _GEN_18 & 16'h5555,
       _GEN_18[1],
       _GEN_21[21] | _GEN_14[2],
       {_GEN_14[3], 1'h0} | _GEN_19 & 2'h1,
       _GEN_21[18:15] | {io_in1[39:38], io_in1[41:40]} & 4'h5,
       _GEN_21[14:7] | _GEN_20 & 8'h55,
       _GEN_20[1],
       _GEN_21[5] | io_in1[50],
       io_in1[51],
       io_in1[52],
       {_GEN_21[2:0], 1'h0} | {io_in1[55:54], io_in1[57:56]} & 4'h5,
       io_in1[57],
       io_in1[58],
       io_in1[59],
       io_in1[60],
       io_in1[61],
       io_in1[62],
       io_in1[63]}},
     {io_in1}};
  wire             _out_T = io_fn == 5'h0;
  wire             _out_T_2 = io_fn == 5'hA;
  wire [63:0]      out =
    _out_T_2 | _out_T
      ? _io_adder_out_T_3
      : {63'h0, io_fn > 5'hB & ~(io_fn[4]) & slt} | (_logic_T_6 ? in1_xor_in2 : 64'h0)
        | (_logic_T_14 ? io_in1 & in2_inv : 64'h0)
        | (_shout_T_4 ? _shout_r_T_5[63:0] : 64'h0)
        | (_shout_T_6
             ? {_shout_r_T_5[0],
                _shout_r_T_5[1],
                _shout_r_T_5[2],
                _shout_r_T_5[3],
                _shout_r_T_5[4],
                _GEN_13[50:47] | {_shout_r_T_5[7:6], _shout_r_T_5[9:8]} & 4'h5,
                _GEN_13[46:39] | _GEN_9 & 8'h55,
                _GEN_13[38:23] | _GEN_10 & 16'h5555,
                _GEN_10[1],
                _GEN_13[21] | _GEN_7[2],
                {_GEN_7[3], 1'h0} | _GEN_11 & 2'h1,
                _GEN_13[18:15] | {_shout_r_T_5[39:38], _shout_r_T_5[41:40]} & 4'h5,
                _GEN_13[14:7] | _GEN_12 & 8'h55,
                _GEN_12[1],
                _GEN_13[5] | _shout_r_T_5[50],
                _shout_r_T_5[51],
                _shout_r_T_5[52],
                {_GEN_13[2:0], 1'h0} | {_shout_r_T_5[55:54], _shout_r_T_5[57:56]} & 4'h5,
                _shout_r_T_5[57],
                _shout_r_T_5[58],
                _shout_r_T_5[59],
                _shout_r_T_5[60],
                _shout_r_T_5[61],
                _shout_r_T_5[62],
                _shout_r_T_5[63]}
             : 64'h0);
  assign io_out = io_dw ? out : {{32{out[31]}}, out[31:0]};
  assign io_adder_out = _io_adder_out_T_3;
  assign io_cmp_out = _io_cmp_out_output;
  assign _mux_cond_RocketALU__M__RocketALU__S___bext_mask_T_1 = 1'h0;
  assign _mux_cond_RocketALU__M__RocketALU__S___in2_inv_T = io_fn[3];
  assign _mux_cond_RocketALU__M__RocketALU__S___io_cmp_out_T_2 = ~(io_fn[3]);
  assign _mux_cond_RocketALU__M__RocketALU__S___io_out_T_1 = out[31];
  assign _mux_cond_RocketALU__M__RocketALU__S___logic_T_14 = _logic_T_14;
  assign _mux_cond_RocketALU__M__RocketALU__S___logic_T_6 = _logic_T_6;
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_1 = |(io_in1[7:0]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_10 = |(io_in1[31:24]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_13 = |(io_in1[39:32]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_16 = |(io_in1[47:40]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_19 = |(io_in1[55:48]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_22 = |(io_in1[63:56]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_4 = |(io_in1[15:8]);
  assign _mux_cond_RocketALU__M__RocketALU__S___orcb_T_7 = |(io_in1[23:16]);
  assign _mux_cond_RocketALU__M__RocketALU__S___out_T = _out_T;
  assign _mux_cond_RocketALU__M__RocketALU__S___out_T_2 = _out_T_2;
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T = io_in2[1];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_1 = ~io_dw;
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_10 = _GEN_25[_tz_in_T_3][5];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_11 = _GEN_25[_tz_in_T_3][6];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_12 = _GEN_25[_tz_in_T_3][7];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_13 = _GEN_25[_tz_in_T_3][8];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_14 = _GEN_25[_tz_in_T_3][9];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_15 = _GEN_25[_tz_in_T_3][10];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_16 = _GEN_25[_tz_in_T_3][11];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_17 = _GEN_25[_tz_in_T_3][12];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_18 = _GEN_25[_tz_in_T_3][13];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_19 = _GEN_25[_tz_in_T_3][14];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_20 = _GEN_25[_tz_in_T_3][15];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_21 = _GEN_25[_tz_in_T_3][16];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_22 = _GEN_25[_tz_in_T_3][17];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_23 = _GEN_25[_tz_in_T_3][18];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_24 = _GEN_25[_tz_in_T_3][19];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_25 = _GEN_25[_tz_in_T_3][20];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_26 = _GEN_25[_tz_in_T_3][21];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_27 = _GEN_25[_tz_in_T_3][22];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_28 = _GEN_25[_tz_in_T_3][23];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_29 = _GEN_25[_tz_in_T_3][24];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_30 = _GEN_25[_tz_in_T_3][25];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_31 = _GEN_25[_tz_in_T_3][26];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_32 = _GEN_25[_tz_in_T_3][27];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_33 = _GEN_25[_tz_in_T_3][28];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_34 = _GEN_25[_tz_in_T_3][29];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_35 = _GEN_25[_tz_in_T_3][30];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_36 = _GEN_25[_tz_in_T_3][31];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_37 = _GEN_25[_tz_in_T_3][32];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_38 = _GEN_25[_tz_in_T_3][33];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_39 = _GEN_25[_tz_in_T_3][34];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_40 = _GEN_25[_tz_in_T_3][35];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_41 = _GEN_25[_tz_in_T_3][36];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_42 = _GEN_25[_tz_in_T_3][37];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_43 = _GEN_25[_tz_in_T_3][38];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_44 = _GEN_25[_tz_in_T_3][39];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_45 = _GEN_25[_tz_in_T_3][40];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_46 = _GEN_25[_tz_in_T_3][41];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_47 = _GEN_25[_tz_in_T_3][42];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_48 = _GEN_25[_tz_in_T_3][43];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_49 = _GEN_25[_tz_in_T_3][44];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_5 = _GEN_25[_tz_in_T_3][0];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_50 = _GEN_25[_tz_in_T_3][45];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_51 = _GEN_25[_tz_in_T_3][46];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_52 = _GEN_25[_tz_in_T_3][47];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_53 = _GEN_25[_tz_in_T_3][48];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_54 = _GEN_25[_tz_in_T_3][49];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_55 = _GEN_25[_tz_in_T_3][50];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_56 = _GEN_25[_tz_in_T_3][51];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_57 = _GEN_25[_tz_in_T_3][52];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_58 = _GEN_25[_tz_in_T_3][53];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_59 = _GEN_25[_tz_in_T_3][54];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_6 = _GEN_25[_tz_in_T_3][1];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_60 = _GEN_25[_tz_in_T_3][55];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_61 = _GEN_25[_tz_in_T_3][56];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_62 = _GEN_25[_tz_in_T_3][57];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_63 = _GEN_25[_tz_in_T_3][58];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_64 = _GEN_25[_tz_in_T_3][59];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_65 = _GEN_25[_tz_in_T_3][60];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_66 = _GEN_25[_tz_in_T_3][61];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_67 = _GEN_25[_tz_in_T_3][62];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_68 = _GEN_25[_tz_in_T_3][63];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_69 = 1'h1;
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_7 = _GEN_25[_tz_in_T_3][2];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_8 = _GEN_25[_tz_in_T_3][3];
  assign _mux_cond_RocketALU__M__RocketALU__S___popc_in_T_9 = _GEN_25[_tz_in_T_3][4];
  assign _mux_cond_RocketALU__M__RocketALU__S___rot_shamt_T = ~io_dw;
  assign _mux_cond_RocketALU__M__RocketALU__S___rotin_T = io_fn[0];
  assign _mux_cond_RocketALU__M__RocketALU__S___rotout_T = io_fn[0];
  assign _mux_cond_RocketALU__M__RocketALU__S___rotout_T_2 = io_fn[0];
  assign _mux_cond_RocketALU__M__RocketALU__S___shin_T_7 = ~_shin_T_6;
  assign _mux_cond_RocketALU__M__RocketALU__S___shin_hi_32_T_3 = _shin_hi_32_T_3;
  assign _mux_cond_RocketALU__M__RocketALU__S___shin_hi_T = io_dw;
  assign _mux_cond_RocketALU__M__RocketALU__S___shout_T_4 = _shout_T_4;
  assign _mux_cond_RocketALU__M__RocketALU__S___shout_T_6 = _shout_T_6;
  assign _mux_cond_RocketALU__M__RocketALU__S___slt_T_2 = _slt_T_2;
  assign _mux_cond_RocketALU__M__RocketALU__S___slt_T_4 = io_fn[1];
  assign _mux_cond_RocketALU__M__RocketALU__S___tz_in_T_116 = _tz_in_T_3 == 2'h1;
  assign _mux_cond_RocketALU__M__RocketALU__S___tz_in_T_118 = _tz_in_T_3 == 2'h2;
  assign _mux_cond_RocketALU__M__RocketALU__S___tz_in_T_120 = &_tz_in_T_3;
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_12 = io_in2[11:0] == 12'h287;
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_14 = io_in2[11:0] == 12'h6B8;
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_16 = io_in2[11:0] == 12'h80;
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_18 = io_in2[11:0] == 12'h604;
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_20 = io_in2[11:0] == 12'h605;
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_3 = io_in1[7];
  assign _mux_cond_RocketALU__M__RocketALU__S___unary_T_8 = io_in1[15];
  assign _mux_cond_RocketALU__M__RocketALU__S__io__s__cmp_out = _io_cmp_out_output;
  assign _cond_pred_RocketALU__M__RocketALU__S___T_1 = ~io_dw;
endmodule

