// Generated by CIRCT firtool-1.43.0
module RocketALU(
  input         clock,
                reset,
                io_dw,
  input  [4:0]  io_fn,
  input  [63:0] io_in2,
                io_in1,
  output [63:0] io_out,
                io_adder_out,
  output        io_cmp_out,
                _mc__s0,
                _mc__s1,
                _mc__s10,
                _mc__s100,
                _mc__s101,
                _mc__s102,
                _mc__s103,
                _mc__s104,
                _mc__s11,
                _mc__s12,
                _mc__s13,
                _mc__s14,
                _mc__s15,
                _mc__s16,
                _mc__s17,
                _mc__s18,
                _mc__s19,
                _mc__s2,
                _mc__s20,
                _mc__s21,
                _mc__s22,
                _mc__s23,
                _mc__s24,
                _mc__s25,
                _mc__s26,
                _mc__s27,
                _mc__s28,
                _mc__s29,
                _mc__s3,
                _mc__s30,
                _mc__s31,
                _mc__s32,
                _mc__s33,
                _mc__s34,
                _mc__s35,
                _mc__s36,
                _mc__s37,
                _mc__s38,
                _mc__s39,
                _mc__s4,
                _mc__s40,
                _mc__s41,
                _mc__s42,
                _mc__s43,
                _mc__s44,
                _mc__s45,
                _mc__s46,
                _mc__s47,
                _mc__s48,
                _mc__s49,
                _mc__s5,
                _mc__s50,
                _mc__s51,
                _mc__s52,
                _mc__s53,
                _mc__s54,
                _mc__s55,
                _mc__s56,
                _mc__s57,
                _mc__s58,
                _mc__s59,
                _mc__s6,
                _mc__s60,
                _mc__s61,
                _mc__s62,
                _mc__s63,
                _mc__s64,
                _mc__s65,
                _mc__s66,
                _mc__s67,
                _mc__s68,
                _mc__s69,
                _mc__s7,
                _mc__s70,
                _mc__s71,
                _mc__s72,
                _mc__s73,
                _mc__s74,
                _mc__s75,
                _mc__s76,
                _mc__s77,
                _mc__s78,
                _mc__s79,
                _mc__s8,
                _mc__s80,
                _mc__s81,
                _mc__s82,
                _mc__s83,
                _mc__s84,
                _mc__s85,
                _mc__s86,
                _mc__s87,
                _mc__s88,
                _mc__s89,
                _mc__s9,
                _mc__s90,
                _mc__s91,
                _mc__s92,
                _mc__s93,
                _mc__s94,
                _mc__s95,
                _mc__s96,
                _mc__s97,
                _mc__s98,
                _mc__s99,
                _cp__s0
);

  wire [63:0]      in2_inv = {64{io_fn[3]}} ^ io_in2;
  wire [63:0]      in1_xor_in2 = io_in1 ^ in2_inv;
  wire [63:0]      _io_adder_out_output = io_in1 + in2_inv + {63'h0, io_fn[3]};
  wire             _GEN = io_in1[63] == io_in2[63];
  wire             slt =
    _GEN ? _io_adder_out_output[63] : io_fn[1] ? io_in2[63] : io_in1[63];
  wire             _io_cmp_out_output =
    io_fn[0] ^ (io_fn[3] ? slt : in1_xor_in2 == 64'h0);
  wire             _GEN_0 = io_fn[3] & io_in1[31];
  wire [31:0]      shin_hi = io_dw ? io_in1[63:32] : {32{_GEN_0}};
  wire             _GEN_1 = io_fn == 5'h13;
  wire             _GEN_2 = io_fn == 5'h5 | io_fn == 5'hB;
  wire             _GEN_3 = _GEN_2 | io_fn == 5'h12 | _GEN_1;
  wire [31:0]      _GEN_4 = {io_in1[31:16], 16'h0} | shin_hi & 32'hFFFF;
  wire [31:0]      _GEN_5 =
    {{io_in1[15:0], _GEN_4[31:24]} & 24'hFF00FF, 8'h0} | _GEN_4 & 32'hFF00FF;
  wire [31:0]      _GEN_6 =
    {{io_in1[7:0], _GEN_5[31:12]} & 28'hF0F0F0F, 4'h0} | _GEN_5 & 32'hF0F0F0F;
  wire [45:0]      _GEN_7 =
    {io_in1[3:0], _GEN_6, _GEN_5[7:4], _GEN_4[11:8], _GEN_4[15:14]} & 46'h333333333333;
  wire [31:0]      _GEN_8 = _GEN_7[45:14] | _GEN_6 & 32'h33333333;
  wire [1:0]       _GEN_9 = _GEN_7[11:10] | _GEN_5[5:4];
  wire [7:0]       _GEN_10 =
    {_GEN_7[5:0], 2'h0} | {_GEN_4[15:12], shin_hi[19:16]} & 8'h33;
  wire [54:0]      _GEN_11 =
    {io_in1[1:0],
     _GEN_8,
     _GEN_6[3:2],
     _GEN_9,
     _GEN_5[7:6],
     _GEN_4[9:8],
     _GEN_10,
     shin_hi[19:18],
     shin_hi[21:20],
     shin_hi[23]} & 55'h55555555555555;
  wire [63:0]      shin =
    _GEN_3
      ? {shin_hi, io_in1[31:0]}
      : {io_in1[0],
         _GEN_11[54:23] | _GEN_8 & 32'h55555555,
         _GEN_8[1],
         _GEN_11[21] | _GEN_6[2],
         {_GEN_6[3], 1'h0} | _GEN_9 & 2'h1,
         _GEN_11[18:15] | {_GEN_5[7:6], _GEN_4[9:8]} & 4'h5,
         _GEN_11[14:7] | _GEN_10 & 8'h55,
         _GEN_10[1],
         _GEN_11[5] | shin_hi[18],
         shin_hi[19],
         shin_hi[20],
         {_GEN_11[2:0], 1'h0} | {shin_hi[23:22], shin_hi[25:24]} & 4'h5,
         shin_hi[25],
         shin_hi[26],
         shin_hi[27],
         shin_hi[28],
         shin_hi[29],
         shin_hi[30],
         shin_hi[31]};
  wire [64:0]      _GEN_12 =
    $signed($signed({io_fn[3] & shin[63], shin})
            >>> {59'h0, io_in2[5] & io_dw, io_in2[4:0]});
  wire [15:0]      _GEN_13 =
    {{_GEN_12[23:16], _GEN_12[31:28]} & 12'hF0F, 4'h0} | {_GEN_12[31:24], _GEN_12[39:32]}
    & 16'hF0F;
  wire [37:0]      _GEN_14 =
    {_GEN_12[11:8],
     _GEN_12[15:12],
     _GEN_12[19:16],
     _GEN_13,
     _GEN_12[39:36],
     _GEN_12[43:40],
     _GEN_12[47:46]} & 38'h3333333333;
  wire [7:0]       _GEN_15 = _GEN_14[37:30] | {_GEN_12[15:12], _GEN_12[19:16]} & 8'h33;
  wire [15:0]      _GEN_16 = _GEN_14[29:14] | _GEN_13 & 16'h3333;
  wire [1:0]       _GEN_17 = _GEN_14[11:10] | _GEN_12[37:36];
  wire [7:0]       _GEN_18 =
    {_GEN_14[5:0], 2'h0} | {_GEN_12[47:44], _GEN_12[51:48]} & 8'h33;
  wire [50:0]      _GEN_19 =
    {_GEN_12[5:4],
     _GEN_12[7:6],
     _GEN_12[9:8],
     _GEN_15,
     _GEN_16,
     _GEN_13[3:2],
     _GEN_17,
     _GEN_12[39:38],
     _GEN_12[41:40],
     _GEN_18,
     _GEN_12[51:50],
     _GEN_12[53:52],
     _GEN_12[55]} & 51'h5555555555555;
  wire             _GEN_20 = _GEN_2 | _GEN_1;
  wire             _GEN_21 = io_fn == 5'h1;
  wire             _GEN_22 = io_fn == 5'h6;
  wire             _GEN_23 = io_fn == 5'h19;
  wire             _GEN_24 = io_fn == 5'h4 | _GEN_22 | _GEN_23 | io_fn == 5'h1A;
  wire             _GEN_25 = _GEN_22 | io_fn == 5'h7 | _GEN_23 | io_fn == 5'h18;
  wire [1:0]       _GEN_26 = {~io_dw, ~(io_in2[0])};
  wire [15:0]      _GEN_27 =
    {{io_in1[23:16], io_in1[31:28]} & 12'hF0F, 4'h0} | {io_in1[31:24], io_in1[39:32]}
    & 16'hF0F;
  wire [37:0]      _GEN_28 =
    {io_in1[11:8],
     io_in1[15:12],
     io_in1[19:16],
     _GEN_27,
     io_in1[39:36],
     io_in1[43:40],
     io_in1[47:46]} & 38'h3333333333;
  wire [7:0]       _GEN_29 = {io_in1[15:12], io_in1[19:16]} & 8'h33;
  wire [7:0]       _GEN_30 = _GEN_28[37:30] | _GEN_29;
  wire [15:0]      _GEN_31 = _GEN_28[29:14] | _GEN_27 & 16'h3333;
  wire [1:0]       _GEN_32 = _GEN_28[11:10] | io_in1[37:36];
  wire [7:0]       _GEN_33 =
    {_GEN_28[5:0], 2'h0} | {io_in1[47:44], io_in1[51:48]} & 8'h33;
  wire [50:0]      _GEN_34 =
    {io_in1[5:4],
     io_in1[7:6],
     io_in1[9:8],
     _GEN_30,
     _GEN_31,
     _GEN_27[3:2],
     _GEN_32,
     io_in1[39:38],
     io_in1[41:40],
     _GEN_33,
     io_in1[51:50],
     io_in1[53:52],
     io_in1[55]} & 51'h5555555555555;
  wire [3:0]       _GEN_35 = {io_in1[7:6], io_in1[9:8]} & 4'h5;
  wire [7:0]       _GEN_36 = {{io_in1[11:8], io_in1[15:14]} & 6'h33, 2'h0} | _GEN_29;
  wire [18:0]      _GEN_37 =
    {io_in1[5:4],
     io_in1[7:6],
     io_in1[9:8],
     _GEN_36,
     io_in1[19:18],
     io_in1[21:20],
     io_in1[23]} & 19'h55555;
  wire [3:0][63:0] _GEN_38 =
    {{{32'h1,
       io_in1[0],
       io_in1[1],
       io_in1[2],
       io_in1[3],
       io_in1[4],
       _GEN_37[18:15] | _GEN_35,
       _GEN_37[14:7] | _GEN_36 & 8'h55,
       _GEN_36[1],
       _GEN_37[5] | io_in1[18],
       io_in1[19],
       io_in1[20],
       {_GEN_37[2:0], 1'h0} | {io_in1[23:22], io_in1[25:24]} & 4'h5,
       io_in1[25],
       io_in1[26],
       io_in1[27],
       io_in1[28],
       io_in1[29],
       io_in1[30],
       io_in1[31]}},
     {{32'h1, io_in1[31:0]}},
     {{io_in1[0],
       io_in1[1],
       io_in1[2],
       io_in1[3],
       io_in1[4],
       _GEN_34[50:47] | _GEN_35,
       _GEN_34[46:39] | _GEN_30 & 8'h55,
       _GEN_34[38:23] | _GEN_31 & 16'h5555,
       _GEN_31[1],
       _GEN_34[21] | _GEN_27[2],
       {_GEN_27[3], 1'h0} | _GEN_32 & 2'h1,
       _GEN_34[18:15] | {io_in1[39:38], io_in1[41:40]} & 4'h5,
       _GEN_34[14:7] | _GEN_33 & 8'h55,
       _GEN_33[1],
       _GEN_34[5] | io_in1[50],
       io_in1[51],
       io_in1[52],
       {_GEN_34[2:0], 1'h0} | {io_in1[55:54], io_in1[57:56]} & 4'h5,
       io_in1[57],
       io_in1[58],
       io_in1[59],
       io_in1[60],
       io_in1[61],
       io_in1[62],
       io_in1[63]}},
     {io_in1}};
  wire             _GEN_39 = io_fn == 5'h0;
  wire             _GEN_40 = io_fn == 5'hA;
  wire [63:0]      out =
    _GEN_40 | _GEN_39
      ? _io_adder_out_output
      : {63'h0, io_fn > 5'hB & ~(io_fn[4]) & slt} | (_GEN_24 ? in1_xor_in2 : 64'h0)
        | (_GEN_25 ? io_in1 & in2_inv : 64'h0) | (_GEN_20 ? _GEN_12[63:0] : 64'h0)
        | (_GEN_21
             ? {_GEN_12[0],
                _GEN_12[1],
                _GEN_12[2],
                _GEN_12[3],
                _GEN_12[4],
                _GEN_19[50:47] | {_GEN_12[7:6], _GEN_12[9:8]} & 4'h5,
                _GEN_19[46:39] | _GEN_15 & 8'h55,
                _GEN_19[38:23] | _GEN_16 & 16'h5555,
                _GEN_16[1],
                _GEN_19[21] | _GEN_13[2],
                {_GEN_13[3], 1'h0} | _GEN_17 & 2'h1,
                _GEN_19[18:15] | {_GEN_12[39:38], _GEN_12[41:40]} & 4'h5,
                _GEN_19[14:7] | _GEN_18 & 8'h55,
                _GEN_18[1],
                _GEN_19[5] | _GEN_12[50],
                _GEN_12[51],
                _GEN_12[52],
                {_GEN_19[2:0], 1'h0} | {_GEN_12[55:54], _GEN_12[57:56]} & 4'h5,
                _GEN_12[57],
                _GEN_12[58],
                _GEN_12[59],
                _GEN_12[60],
                _GEN_12[61],
                _GEN_12[62],
                _GEN_12[63]}
             : 64'h0);
  assign io_out = io_dw ? out : {{32{out[31]}}, out[31:0]};
  assign io_adder_out = _io_adder_out_output;
  assign io_cmp_out = _io_cmp_out_output;
  assign _mc__s0 = io_fn[3];
  assign _mc__s1 = io_fn[1];
  assign _mc__s10 = _GEN_25;
  assign _mc__s100 = io_fn[0];
  assign _mc__s101 = io_fn[0];
  assign _mc__s102 = _GEN_39;
  assign _mc__s103 = _GEN_40;
  assign _mc__s104 = out[31];
  assign _mc__s11 = 1'h0;
  assign _mc__s12 = _GEN_26 == 2'h1;
  assign _mc__s13 = _GEN_26 == 2'h2;
  assign _mc__s14 = &_GEN_26;
  assign _mc__s15 = ~io_dw;
  assign _mc__s16 = 1'h1;
  assign _mc__s17 = _GEN_38[_GEN_26][63];
  assign _mc__s18 = _GEN_38[_GEN_26][62];
  assign _mc__s19 = _GEN_38[_GEN_26][61];
  assign _mc__s2 = _GEN;
  assign _mc__s20 = _GEN_38[_GEN_26][60];
  assign _mc__s21 = _GEN_38[_GEN_26][59];
  assign _mc__s22 = _GEN_38[_GEN_26][58];
  assign _mc__s23 = _GEN_38[_GEN_26][57];
  assign _mc__s24 = _GEN_38[_GEN_26][56];
  assign _mc__s25 = _GEN_38[_GEN_26][55];
  assign _mc__s26 = _GEN_38[_GEN_26][54];
  assign _mc__s27 = _GEN_38[_GEN_26][53];
  assign _mc__s28 = _GEN_38[_GEN_26][52];
  assign _mc__s29 = _GEN_38[_GEN_26][51];
  assign _mc__s3 = ~(io_fn[3]);
  assign _mc__s30 = _GEN_38[_GEN_26][50];
  assign _mc__s31 = _GEN_38[_GEN_26][49];
  assign _mc__s32 = _GEN_38[_GEN_26][48];
  assign _mc__s33 = _GEN_38[_GEN_26][47];
  assign _mc__s34 = _GEN_38[_GEN_26][46];
  assign _mc__s35 = _GEN_38[_GEN_26][45];
  assign _mc__s36 = _GEN_38[_GEN_26][44];
  assign _mc__s37 = _GEN_38[_GEN_26][43];
  assign _mc__s38 = _GEN_38[_GEN_26][42];
  assign _mc__s39 = _GEN_38[_GEN_26][41];
  assign _mc__s4 = _GEN_0;
  assign _mc__s40 = _GEN_38[_GEN_26][40];
  assign _mc__s41 = _GEN_38[_GEN_26][39];
  assign _mc__s42 = _GEN_38[_GEN_26][38];
  assign _mc__s43 = _GEN_38[_GEN_26][37];
  assign _mc__s44 = _GEN_38[_GEN_26][36];
  assign _mc__s45 = _GEN_38[_GEN_26][35];
  assign _mc__s46 = _GEN_38[_GEN_26][34];
  assign _mc__s47 = _GEN_38[_GEN_26][33];
  assign _mc__s48 = _GEN_38[_GEN_26][32];
  assign _mc__s49 = _GEN_38[_GEN_26][31];
  assign _mc__s5 = io_dw;
  assign _mc__s50 = _GEN_38[_GEN_26][30];
  assign _mc__s51 = _GEN_38[_GEN_26][29];
  assign _mc__s52 = _GEN_38[_GEN_26][28];
  assign _mc__s53 = _GEN_38[_GEN_26][27];
  assign _mc__s54 = _GEN_38[_GEN_26][26];
  assign _mc__s55 = _GEN_38[_GEN_26][25];
  assign _mc__s56 = _GEN_38[_GEN_26][24];
  assign _mc__s57 = _GEN_38[_GEN_26][23];
  assign _mc__s58 = _GEN_38[_GEN_26][22];
  assign _mc__s59 = _GEN_38[_GEN_26][21];
  assign _mc__s6 = ~_GEN_3;
  assign _mc__s60 = _GEN_38[_GEN_26][20];
  assign _mc__s61 = _GEN_38[_GEN_26][19];
  assign _mc__s62 = _GEN_38[_GEN_26][18];
  assign _mc__s63 = _GEN_38[_GEN_26][17];
  assign _mc__s64 = _GEN_38[_GEN_26][16];
  assign _mc__s65 = _GEN_38[_GEN_26][15];
  assign _mc__s66 = _GEN_38[_GEN_26][14];
  assign _mc__s67 = _GEN_38[_GEN_26][13];
  assign _mc__s68 = _GEN_38[_GEN_26][12];
  assign _mc__s69 = _GEN_38[_GEN_26][11];
  assign _mc__s7 = _GEN_20;
  assign _mc__s70 = _GEN_38[_GEN_26][10];
  assign _mc__s71 = _GEN_38[_GEN_26][9];
  assign _mc__s72 = _GEN_38[_GEN_26][8];
  assign _mc__s73 = _GEN_38[_GEN_26][7];
  assign _mc__s74 = _GEN_38[_GEN_26][6];
  assign _mc__s75 = _GEN_38[_GEN_26][5];
  assign _mc__s76 = _GEN_38[_GEN_26][4];
  assign _mc__s77 = _GEN_38[_GEN_26][3];
  assign _mc__s78 = _GEN_38[_GEN_26][2];
  assign _mc__s79 = _GEN_38[_GEN_26][1];
  assign _mc__s8 = _GEN_21;
  assign _mc__s80 = _GEN_38[_GEN_26][0];
  assign _mc__s81 = io_in2[1];
  assign _mc__s82 = |(io_in1[7:0]);
  assign _mc__s83 = |(io_in1[15:8]);
  assign _mc__s84 = |(io_in1[23:16]);
  assign _mc__s85 = |(io_in1[31:24]);
  assign _mc__s86 = |(io_in1[39:32]);
  assign _mc__s87 = |(io_in1[47:40]);
  assign _mc__s88 = |(io_in1[55:48]);
  assign _mc__s89 = |(io_in1[63:56]);
  assign _mc__s9 = _GEN_24;
  assign _mc__s90 = io_in1[7];
  assign _mc__s91 = io_in1[15];
  assign _mc__s92 = io_in2[11:0] == 12'h287;
  assign _mc__s93 = io_in2[11:0] == 12'h6B8;
  assign _mc__s94 = io_in2[11:0] == 12'h80;
  assign _mc__s95 = io_in2[11:0] == 12'h604;
  assign _mc__s96 = io_in2[11:0] == 12'h605;
  assign _mc__s97 = _io_cmp_out_output;
  assign _mc__s98 = ~io_dw;
  assign _mc__s99 = io_fn[0];
  assign _cp__s0 = ~io_dw;
endmodule

